#!/usr/bin/python3

from tokeniser import *
from parser import *

import json
def main(argv):
  try:
    argv[1]
  except IndexError:
    print("No input file specified...")
    exit(1)

  try:
    argv[2]
  except IndexError:
    print("No output file specified...")
    exit(1)
  
  global SOURCE_FILE
  SOURCE_FILE = argv[1]
  tokens = tokenise(SOURCE_FILE)
  program = parse(tokens)
  with open(argv[2], "w+") as output:
    output.truncate(0)
    output.write(" ".join(list(map(lambda v: "{:02x}".format(v), list(json.dumps(program.toDictionary()).encode("utf-8"))))))

import sys 
if __name__ == "__main__":
  main(sys.argv)