#!/usr/bin/python3

from utils import readInput
from env import Env, buildEnv

def main(argv):
	try:
		argv[1]
	except IndexError:
		print("No input file specified...")
		exit(1)

	try:
		environ = readInput(argv[1])
	except Exception as e:
		print("Invalid source file...")
		exit(2)

	env = buildEnv(environ, argv[1])
	env.init()
	env.pulse()
	print(env.globals)
	print(env.instances)

import sys
if __name__ == "__main__":
	main(sys.argv)